version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 21
    commands:
      - cd src/main/angular/grafrank
      - npm install
  pre_build:
    - npm i -g @angular/cli
    - npm i -g typescript
    - echo "install nodejs"
  build:
    commands:
      - ng build --prod
      - cd ../../../
      - mvn clean install
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes